#pragma config(Motor,  port2,           chassisBR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           chassisFR,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           chassisBL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chassisFL,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MecanumCommands.C"
task main()
{
while (1==1)
{
if (Ch3 > 28)
{Forward()
}

if (Ch3 < -28)
{Backward()
}

if (Ch4 > 28)
{LeftStrafe()
}

if (Ch4 < -28)
{RightStrafe()
}

if (Ch1 > 28)
{RightTurn()
}

if (Ch1 < -28)
{LeftTurn()
}
}
}
