#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LeftM,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           LeftB,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           RightF,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           RightM,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           RightB,        tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "PhilippVEX.h"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	AllForward();
	wait1Msec(3250);
	allMotorsOff();
}

task usercontrol()
{
	UserLoop();
}
