#pragma config(Motor,  port2,           LeftF,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LeftB,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           RightF,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           RightB,        tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PhilippVEX.h"

task main()
{
	UserLoop();
}
